modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="${project.mod_license}"
[[mods]] #mandatory
modId="bacterium" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional

[[mixins]]
config="bacterium.mixins.json"
description='''${mod_description}'''
[[dependencies."bacterium"]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[20,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies."bacterium"]]
modId="minecraft"
type="required"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
